#!/bin/bash
### --------------------------------- ###
###     Copyright 2016 Luke Higgs     ###
### Contact: admin@aquariandesign.com ###
### --------------------------------- ###

# This file is part of SBU (Snapshot Backup Utility)

# SBU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

# SBU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with SBU (located in /opt/sbu/docs/COPYING).  If not, see <http://www.gnu.org/licenses/>.
#################################################################################################

function checkStatus {
	
	NAME=$1
	PID=0
	STATUS=0
	
	if [ -e "/opt/sbu/jobs/$NAME/$NAME.conf" ]; then

		FILE="/opt/sbu/jobs/$NAME/$NAME.conf"
	
		while read -r line
		do
			[[ $line = \#* ]] && continue
		
			if [[ $line == *"Source"* ]]; then
				SOURCE=$(echo "$line" | cut -d '=' -f 2)
			fi
		
		done < "$FILE"

	#else 
	#	echo $STATUS
	#	exit
	fi
	
	PID1=$(pgrep -f "/opt/sbu/source/create-new-job.sh ${SOURCE}")
	PID2=$(pgrep -f "/opt/sbu/source/run-job.sh $NAME")

	if [[ "$PID1" > 0 || "$PID2" > 0 ]]; then
		STATUS=1
	else
		STATUS=0
	fi
	
	echo $STATUS
	
}

function getCurrentStatus {
	
	NAME=$1
	PID=0
	TOTALSTATUS=""
	
	if [ -e "/opt/sbu/jobs/$NAME/$NAME.conf" ]; then

		FILE="/opt/sbu/jobs/$NAME/$NAME.conf"
	
		while read -r line
		do
			[[ $line = \#* ]] && continue
		
			if [[ $line == *"Source"* ]]; then
				SOURCE=$(echo "$line" | cut -d '=' -f 2)
			fi
		
		done < "$FILE"

	else 
		echo "Could not get $NAME config!"
		#STATUS="$NAME does not exist!"
		#exit
	fi
	
	PID1=$(pgrep -f "/opt/sbu/source/create-new-job.sh ${SOURCE}")
	PID2=$(pgrep -f "/opt/sbu/source/run-job.sh $NAME")
		
	if [[ "$PID1" > 0 || "$PID2" > 0 ]]; then
		
		STATUS="- idle"
		
		if [[ -e "/opt/sbu/jobs/$NAME/$NAME-rolling-up-backup" ]]; then
			STATUS1="rolling up backup"
		fi
		
		if [[ -e "/opt/sbu/jobs/$NAME/$NAME-rotating-backup" ]]; then
			STATUS2="rotating backup"
		fi
		
		if [[ -e "/opt/sbu/jobs/$NAME/$NAME-initializing" ]]; then
			STATUS3="initializing"
		fi
	
		if [[ -e "/opt/sbu/jobs/$NAME/$NAME-currently-taking-snapshot" ]]; then
			STATUS4="currently taking snapshot"
		fi
	
		if [[ -e "/opt/sbu/jobs/$NAME/$NAME-searching" ]]; then
			STATUS5="searching for changes"
		fi
	
		if [[ -e "/opt/sbu/jobs/$NAME/$NAME-syncing-changes" ]]; then
			STATUS6="syncing changes"
		fi
		
	else
		STATUS="is not running!"
	fi
	
	if [[ ! -z "$STATUS1" ]]; then
		TOTALSTATUS=$TOTALSTATUS" - "$STATUS1
	fi
	
	if [[ ! -z "$STATUS2" ]]; then
		TOTALSTATUS=$TOTALSTATUS" - "$STATUS2
	fi
	
	if [[ ! -z "$STATUS3" ]]; then
		TOTALSTATUS=$TOTALSTATUS" - "$STATUS3
	fi
	
	if [[ ! -z "$STATUS4" ]]; then
		TOTALSTATUS=$TOTALSTATUS" - "$STATUS4
	fi
	
	if [[ ! -z "$STATUS5" ]]; then
		TOTALSTATUS=$TOTALSTATUS" - "$STATUS5
	fi
	
	if [[ ! -z "$STATUS6" ]]; then
		TOTALSTATUS=$TOTALSTATUS" - "$STATUS6
	fi
	
	if [[ ! -z "$TOTALSTATUS" ]]; then
		echo $NAME $TOTALSTATUS
	else
		echo $NAME $STATUS
	fi
	
}

function usage {	
	clear
	less /opt/sbu/docs/usage.txt
}
