#!/bin/bash
### --------------------------------- ###
###     Copyright 2016 Luke Higgs     ###
### Contact: admin@aquariandesign.com ###
### --------------------------------- ###

# This file is part of SBU (Snapshot Backup Utility)

# SBU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

# SBU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with SBU (located in /opt/sbu/docs/COPYING).  If not, see <http://www.gnu.org/licenses/>.
#################################################################################################

if [ -e "/opt/sbu/jobs/$1/$1.conf" ]; then

	FILE="/opt/sbu/jobs/$1/$1.conf"
	
	while read -r line
	do
		[[ $line = \#* ]] && continue
		
		if [[ $line == *"Name="* ]]; then
			NAME=$(echo "$line" | cut -d '=' -f 2)
		fi
		
		if [[ $line == *"Source="* ]]; then
			SOURCE=$(echo "$line" | cut -d '=' -f 2)
		fi
		
		if [[ $line == *"Dest="* ]]; then
			DEST=$(echo "$line" | cut -d '=' -f 2)
		fi
		
		if [[ $line == *"Interval="* ]]; then
			INTERVAL=$(echo "$line" | cut -d '=' -f 2)
		fi
		
		if [[ $line == *"Retention="* ]]; then
			RETENTION=$(echo "$line" | cut -d '=' -f 2)
		fi
		
		if [[ $line == *"Autostart="* ]]; then
			AUTOSTART=$(echo "$line" | cut -d '=' -f 2)
		fi
		
		if [[ $line == *"FullSync="* ]]; then
			FULLSYNC=$(echo "$line" | cut -d '=' -f 2)
		fi
		
		if [[ $line == *"DestPerms="* ]]; then
			SETPERMS=$(echo "$line" | cut -d '=' -f 2)
		fi
		
		if [[ $line == *"DestOwner="* ]]; then
			SETOWNER=$(echo "$line" | cut -d '=' -f 2)
		fi
		
		if [[ $line == *"DestGroup="* ]]; then
			SETGROUP=$(echo "$line" | cut -d '=' -f 2)
		fi
		
		if [[ $line == *"ExcludeFile="* ]]; then
			EXCLUDEFILE=$(echo "$line" | cut -d '=' -f 2)
		fi
		
	done < "$FILE"
	
	OPTS=( "-rdltD" )

	# GET PERMISSION SETTINGS:
	if [ "$SETPERMS" == "copy" ]; then
		OPTS=( "-rlptgoD" )
	else
		if [[ $SETPERMS -gt 0 ]]; then
			OPTS=( "-rdltgoD" "--chmod=$SETPERMS" )
		fi
	fi

	if [ -n "$SETGROUP" ] && [ -n "$SETOWNER" ]; then
	
		if [ "$SETGROUP" != "copy" ] && [ "$SETOWNER" != "copy" ]; then
			OPTS+=( "--chown=$SETOWNER:$SETGROUP" )
		fi

	fi
	
	if [ "$SETPERMS" == "no-perms" ]; then
		OPTS=( "-rdltD" )
	fi
	
	if [ -z "$EXCLUDEFILE" ]; then
		if [ ! -e "/opt/sbu/jobs/$NAME/$NAME-exclude-file" ]; then
			touch "/opt/sbu/jobs/$NAME/$NAME-exclude-file"
		fi
		OPTS+=( "--exclude-from=/opt/sbu/jobs/$NAME/$NAME-exclude-file" )
	else
		OPTS+=( "--exclude-from=${EXCLUDEFILE}" )
	fi
	
	#OPTS+=( "--delete" )

else 
	echo "$1 backup job does not exist!"
	#exit
fi
