#!/bin/bash
### --------------------------------- ###
###     Copyright 2016 Luke Higgs     ###
### Contact: admin@aquariandesign.com ###
### --------------------------------- ###

# This file is part of SBU (Snapshot Backup Utility)

# SBU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

# SBU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with SBU (located in /opt/sbu/docs/COPYING).  If not, see <http://www.gnu.org/licenses/>.
#################################################################################################

# load_job_config lives in functions; most callers source it already.
declare -F load_job_config >/dev/null || source /opt/sbu/source/functions

if load_job_config "$1"; then

	OPTS=( "-rdltD" )

	# GET PERMISSION SETTINGS:
	if [ "$SETPERMS" == "copy" ]; then
		OPTS=( "-rlptgoD" )
	else
		if [[ $SETPERMS -gt 0 ]]; then
			OPTS=( "-rdltgoD" "--chmod=$SETPERMS" )
		fi
	fi

	if [ -n "$SETGROUP" ] && [ -n "$SETOWNER" ]; then
	
		if [ "$SETGROUP" != "copy" ] && [ "$SETOWNER" != "copy" ]; then
			OPTS+=( "--chown=$SETOWNER:$SETGROUP" )
		fi

	fi
	
	if [ "$SETPERMS" == "no-perms" ]; then
		OPTS=( "-rdltD" )
	fi
	
	if [ -z "$EXCLUDEFILE" ]; then
		if [ ! -e "/opt/sbu/jobs/$NAME/$NAME-exclude-file" ]; then
			touch "/opt/sbu/jobs/$NAME/$NAME-exclude-file"
		fi
		OPTS+=( "--exclude-from=/opt/sbu/jobs/$NAME/$NAME-exclude-file" )
	else
		OPTS+=( "--exclude-from=${EXCLUDEFILE}" )
	fi
	
	#OPTS+=( "--delete" )

else
	echo "$1 backup job does not exist!"
fi
